modLoader = "javafml"
loaderVersion = "[58,)"
license = "MIT"
issueTrackerURL = "https://github.com/grumpycoders/minerva/issues"

[[mods]]
modId = "minerva"
version = "1.0.0"
displayName = "Minerva"
description = "Minerva is a Minecraft AI assistant that helps you with various tasks in the game, such as crafting, building, and exploring. It provides intelligent suggestions and automates repetitive tasks to enhance your gameplay experience."
authors = "Wade Rooker, Tom Rooker"
credits = "Developed by doomfaller"
logoFile = "assets/minerva/logo.png"
displayURL = "https://github.com/grumpycoders/minerva"
parent = ""

[[dependencies.minerva]]
modId = "forge"
mandatory = true
versionRange = "[58,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.minerva]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.8,1.21.9)"
ordering = "NONE"
side = "BOTH"
